import { Inter } from "next/font/google";
import GlobalButton from "./(page)/components/GlobalButton";
import Header from "./(page)/components/Header";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}

        <div className="fixed bottom-0 right-0">
          <GlobalButton />
        </div>
      </body>
    </html>
  );
}
